spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/streaming

spring.datasource.username=root

spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

server.port=8080

# Límite máximo de un solo archivo
spring.servlet.multipart.max-file-size=50MB
# Límite máximo total de la solicitud
spring.servlet.multipart.max-request-size=50MB
